"""
Zentrale Registry für Produkt-UI-Metadaten.

Wenn du ein neues Produkt hinzufügst, ergänze hier einen Eintrag.
Die UI baut sich automatisch daraus auf.
"""

PRODUKTE = [
    {
        "modul_name": "etf_sparplan",
        "klassen_name": "ETFSparplan",
        "display_name": "ETF-Sparplan",
        "default_aktiv": True,
        "fields": [
            {"key": "start_datum", "label": "Startdatum", "type": "date", "default": "2027-01-01",
             "help": "Datum, ab dem der Sparplan beginnt."},
            {"key": "monatlicher_sparplan", "label": "Monatliche Sparrate (€)", "type": "number", "default": 200.0,
             "help": "Monatlicher Sparbetrag in Euro."},
            {"key": "startkapital", "label": "Startkapital (€)", "type": "number", "default": 0.0,
             "help": "Bereits angespartes Kapital zum Startdatum."},
            {"key": "erwartete_rendite_prozent", "label": "Erwartete Rendite (% p.a.)", "type": "number", "default": 6.0,
             "help": "Jährliche Renditeannahme **vor** Kosten."},
            {"key": "kostenquote_prozent", "label": "Kostenquote (% p.a.)", "type": "number", "default": 0.2,
             "help": "Jährliche Produktkosten (z. B. TER)."},
        ],
        "abgaben_typ": "etf",
    },
    {
        "modul_name": "gesetzliche_rente",
        "klassen_name": "GesetzlicheRente",
        "display_name": "Gesetzliche Rente",
        "default_aktiv": True,
        "fields": [
            {"key": "aktuelle_rentenansprueche", "label": "Aktuelle Rentenansprüche (€/Monat)", "type": "number", "default": 1000.0,
             "help": "Vorhandener bzw. angenommener monatlicher Rentenanspruch."},
            {"key": "rentenanpassung_prozent", "label": "Rentenanpassung (% p.a.)", "type": "number", "default": 1.5,
             "help": "Angenommene jährliche Rentenanpassung."},
            {"key": "aktueller_rentenwert", "label": "Aktueller Rentenwert (€)", "type": "number", "default": 42.52,
             "help": "Verwendeter aktueller Rentenwert (z. B. West 2025: ca. 42,52 €)."},
            {"key": "durchschnittsentgelt", "label": "Durchschnittsentgelt (€/Jahr)", "type": "number", "default": 51944.0,
             "help": "Verwendetes Durchschnittsentgelt zur Berechnung der Rentenpunkte."},
            {"key": "rv_bbg_jahr", "label": "RV-BBG (€/Jahr)", "type": "number", "default": 101400.0,
             "help": "Jährliche Beitragsbemessungsgrenze der Rentenversicherung."},
        ],
        "abgaben_typ": "gesetzlich",
        "caption": "⚠️ Dieses Modul ersetzt keine individuelle Rentenauskunft.",
    },
    {
        "modul_name": "bav",
        "klassen_name": "BetriebsrentebAV",
        "display_name": "Betriebliche Altersvorsorge (bAV)",
        "default_aktiv": False,
        "fields": [
            {"key": "start_datum", "label": "Startdatum", "type": "date", "default": "2026-01-01",
             "help": "Datum, ab dem die Einzahlungen beginnen."},
            {"key": "monatlicher_beitrag_mitarbeiter", "label": "Monatlicher Eigenbeitrag (€)", "type": "number", "default": 100.0,
             "help": "Monatlicher Eigenbeitrag in Euro."},
            {"key": "arbeitgeber_zuschuss_prozent", "label": "Arbeitgeberzuschuss (%)", "type": "number", "default": 15.0,
             "help": "Arbeitgeberzuschuss auf den Eigenbeitrag in Prozent."},
            {"key": "startkapital", "label": "Startkapital (€)", "type": "number", "default": 0.0,
             "help": "Bereits angespartes Kapital."},
            {"key": "startkapital_datum", "label": "Startkapital-Datum", "type": "date", "default": "2026-01-01",
             "help": "Datum, an dem das Startkapital bereits vorhanden war."},
            {"key": "erwartete_rendite_prozent", "label": "Erwartete Rendite (% p.a.)", "type": "number", "default": 4.0,
             "help": "Jährliche Renditeannahme vor Kosten."},
            {"key": "kostenquote_prozent", "label": "Kostenquote (% p.a.)", "type": "number", "default": 1.03,
             "help": "Jährliche Produktkosten."},
            {"key": "dynamik_prozent", "label": "Dynamik (% p.a.)", "type": "number", "default": 0.0,
             "help": "Jährliche automatische Beitragserhöhung."},
        ],
        "has_staffel": True,
        "staffel_columns": [
            {"key": "ab_jahr", "label": "Ab Jahr", "type": "int", "min": 0, "step": 1},
            {"key": "eigenbeitrag", "label": "Eigenbeitrag (€/Monat)", "type": "number", "min": 0.0, "step": 10.0},
        ],
        "staffel_default": [{"ab_jahr": 0, "eigenbeitrag": 100.0}],
        "staffel_caption": "Trage hier die monatlichen Eigenbeiträge ein. Der AG-Zuschuss gilt für alle Stufen.",
        "abgaben_typ": "bav",
    },
    {
        "modul_name": "altersvorsorgedepot",
        "klassen_name": "AltersvorsorgeDepot",
        "display_name": "Altersvorsorge-Depot",
        "default_aktiv": False,
        "fields": [
            {"key": "start_datum", "label": "Startdatum", "type": "date", "default": "2027-01-01",
             "help": "Datum, ab dem die Einzahlungen beginnen."},
            {"key": "monatlicher_eigenbeitrag", "label": "Monatlicher Eigenbeitrag (€)", "type": "number", "default": 150.0,
             "help": "Monatlicher Eigenbeitrag in Euro."},
            {"key": "erwartete_rendite_prozent", "label": "Erwartete Rendite (% p.a.)", "type": "number", "default": 6.0,
             "help": "Jährliche Renditeannahme vor Kosten."},
            {"key": "kostenquote_prozent", "label": "Kostenquote (% p.a.)", "type": "number", "default": 0.2,
             "help": "Jährliche Produktkosten."},
        ],
        "abgaben_typ": "altersvorsorgedepot",
        "caption": "Die Förderlogik (Grundzulage, Kinderzulage etc.) ist Bestandteil des Modells. Anzahl und Geburtsjahre der Kinder werden im Profil eingetragen.",
    },
    {
        "modul_name": "unterstuetzungskasse",
        "klassen_name": "Unterstuetzungskasse",
        "display_name": "Unterstützungskasse",
        "default_aktiv": False,
        "fields": [
            {"key": "start_datum", "label": "Startdatum", "type": "date", "default": "2027-01-01",
             "help": "Datum, ab dem die Einzahlungen beginnen."},
            {"key": "beschaeftigungs_start_datum", "label": "Beschäftigungsbeginn", "type": "date", "default": "2026-01-01",
             "help": "Datum des Beschäftigungsbeginns."},
            {"key": "startkapital", "label": "Startkapital (€)", "type": "number", "default": 0.0,
             "help": "Bereits angespartes Kapital."},
            {"key": "erwartete_rendite_prozent", "label": "Erwartete Rendite (% p.a.)", "type": "number", "default": 4.0,
             "help": "Jährliche Renditeannahme vor Kosten."},
        ],
        "has_staffel": True,
        "staffel_columns": [
            {"key": "ab_jahr", "label": "Ab Jahr", "type": "int", "min": 0, "step": 1},
            {"key": "eigenbeitrag", "label": "Eigenbeitrag (€/Monat)", "type": "number", "min": 0.0, "step": 10.0},
            {"key": "ag_beitrag", "label": "AG-Beitrag (€/Monat)", "type": "number", "min": 0.0, "step": 10.0},
        ],
        "staffel_default": [{"ab_jahr": 0, "eigenbeitrag": 50.0, "ag_beitrag": 50.0}],
        "has_kosten": True,
        "kosten_fields": [
            {"key": "kosten.renditeminderung_prozent", "label": "Renditeminderung (% p.a.)", "type": "number", "default": 2.0,
             "help": "Kosten als jährliche Renditeminderung."},
            {"key": "kosten.beitrag_prozent", "label": "Beitragskosten (%)", "type": "number", "default": 0.0,
             "help": "Prozentuale Kosten auf den Beitrag."},
            {"key": "kosten.fix_monatlich", "label": "Fixe Kosten (€/Monat)", "type": "number", "default": 0.0,
             "help": "Fixe monatliche Verwaltungskosten."},
            {"key": "kosten.psvag_promille", "label": "PSVaG (Promille)", "type": "number", "default": 0.0,
             "help": "PSVaG-Beitrag des Arbeitgebers in Promille."},
        ],
        "abgaben_typ": "bav",
    },
    {
        "modul_name": "aktienrente",
        "klassen_name": "StaatsfondsAktienrente",
        "display_name": "Aktienrente / Staatsfonds",
        "default_aktiv": False,
        "fields": [
            {"key": "start_datum", "label": "Startdatum", "type": "date", "default": "2028-01-01",
             "help": "Datum, ab dem die Einzahlungen beginnen."},
            {"key": "startkapital", "label": "Startkapital (€)", "type": "number", "default": 0.0,
             "help": "Bereits angespartes Kapital."},
            {"key": "erwartete_rendite_prozent", "label": "Erwartete Rendite (% p.a.)", "type": "number", "default": 5.0,
             "help": "Jährliche Renditeannahme vor Kosten."},
            {"key": "kostenquote_prozent", "label": "Kostenquote (% p.a.)", "type": "number", "default": 0.1,
             "help": "Jährliche Produktkosten."},
        ],
        "has_stufenplan": True,
        "stufenplan_columns": [
            {"key": "jahr", "label": "Jahr", "type": "int", "min": 1900, "step": 1},
            {"key": "an_prozent", "label": "AN-Anteil (%)", "type": "number", "min": 0.0, "max": 100.0, "step": 0.25},
            {"key": "ag_prozent", "label": "AG-Anteil (%)", "type": "number", "min": 0.0, "max": 100.0, "step": 0.25},
        ],
        "stufenplan_default": [
            {"jahr": 2028, "an_prozent": 0.25, "ag_prozent": 0.25},
            {"jahr": 2029, "an_prozent": 0.50, "ag_prozent": 0.50},
            {"jahr": 2030, "an_prozent": 0.75, "ag_prozent": 0.75},
            {"jahr": 2031, "an_prozent": 1.00, "ag_prozent": 1.00},
        ],
        "stufenplan_caption": "Beispiel: `1.0` % bedeutet 1 % vom Bruttogehalt.",
        "brutto_from_profil": True,
        "abgaben_typ": "gesetzlich",
    },
]
